# Generated by Django 5.1.7 on 2025-05-16 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0002_remove_pokemon_sprite_url_pokemon_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite_url',
            field=models.URLField(default="It is impossible to add a non-nullable field 'sprite_url' to pokemon without specifying a default. This is because the database needs something to populate existing rows."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
